name: AdWords Nerds
favicon: null
layout_spectrum: 0.50979
typography_spectrum: 0.24539
title: 'AdWords Nerds | AdWords Help For Real Estate Investors'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#29aae1'
    - '#292929'
    - '#00ffff'
    - '#e82a32'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
